#!/usr/bin/env python3
"""Write docs/data.js from the ranked Actions and the honesty panel."""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DOCS = ROOT / "docs"


def main() -> int:
    d = json.loads((DATA / "actions.json").read_text())
    hp = d.get("honesty_panel")
    if isinstance(hp, str):
        p = ROOT / hp
        d["honesty_panel"] = json.loads(p.read_text()) if p.exists() else {}
    DOCS.mkdir(parents=True, exist_ok=True)
    out = "/* generated by study/build_page_data.py, do not edit */\nconst D = " + \
        json.dumps(d, separators=(",", ":")) + ";\n"
    (DOCS / "data.js").write_text(out)
    print(f"wrote docs/data.js ({len(out)//1024} KB), {len(d['actions'])} candidate Actions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
