#!/usr/bin/env python3
"""Write docs/data.js from the ranked Actions and the honesty panel."""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DOCS = ROOT / "docs"


def attach_stability(d: dict) -> None:
    """Inline data/derived/stability.json, but only if it describes THIS ranking.

    stability.py has to run after rank.py, because it bootstraps the published
    candidates. That means a rebuild which reruns rank.py without rerunning
    stability.py leaves a stability file describing a ranking that no longer
    exists, and inlining it blind would put confidence bands from one ordering
    next to a different ordering. So the file is checked against the actions it
    claims to describe and dropped, loudly, when it does not match.
    """
    p = DATA / "derived" / "stability.json"
    if not p.exists():
        d["stability"] = {"available": False, "reason": "stability.json not built"}
        return
    s = json.loads(p.read_text())
    by = s.get("by_action", {})
    published = {a["action_id"]: a["rank"] for a in d["actions"]}
    stale = [
        aid for aid, rank in published.items()
        if by.get(aid, {}).get("published_rank") != rank
    ]
    if stale:
        d["stability"] = {
            "available": False,
            "reason": (
                f"stability.json describes a different ranking "
                f"({len(stale)} of {len(published)} candidates disagree). "
                "Rerun study/stability.py after rank.py."
            ),
        }
        print(f"  stability.json is STALE for {len(stale)} candidates, not inlined")
        return
    s["available"] = True
    d["stability"] = s
    print(f"  stability.json inlined, {s.get('resamples')} resamples")


def main() -> int:
    d = json.loads((DATA / "actions.json").read_text())
    hp = d.get("honesty_panel")
    if isinstance(hp, str):
        p = ROOT / hp
        d["honesty_panel"] = json.loads(p.read_text()) if p.exists() else {}
    attach_stability(d)
    DOCS.mkdir(parents=True, exist_ok=True)
    out = "/* generated by study/build_page_data.py, do not edit */\nconst D = " + \
        json.dumps(d, separators=(",", ":")) + ";\n"
    (DOCS / "data.js").write_text(out)
    print(f"wrote docs/data.js ({len(out)//1024} KB), {len(d['actions'])} candidate Actions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
